### ISSUE TITLE
CREATOR OWNER fails

### ISSUE THREAD

**Issue by tomcek42** [vBrit/DEM-FSLogix#1]
I'am getting one error during script-run. It has something to do Creator Owner.

ICACLS : CREATOR OWNER: Zuordnungen von Kontennamen und Sicherheitskennungen wurden nicht durchgefhrt.
In C:\Users\xxxx\Desktop\DEM-FSLogix-main\DEMFolderCreate.ps1:62 Zeichen:1
+ ICACLS ("$DEMProfilesDirectory") /grant ("CREATOR OWNER" + ':(OI)(CI) ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CREATOR OWNER: ...t durchgefhrt.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by vBrit** [comment]
Hi, Do you elevate the power shell?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: tomcek ***@***.***>
Sent: Tuesday, January 10, 2023 5:16:30 AM
To: vBrit/DEM-FSLogix ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vBrit/DEM-FSLogix] CREATOR OWNER fails (Issue #1)


I'am getting one error during script-run. It has something to do Creator Owner.

ICACLS : CREATOR OWNER: Zuordnungen von Kontennamen und Sicherheitskennungen wurden nicht durchgef�hrt.
In C:\Users\xxxx\Desktop\DEM-FSLogix-main\DEMFolderCreate.ps1:62 Zeichen:1

  *   ICACLS ("$DEMProfilesDirectory") /grant ("CREATOR OWNER" + ':(OI)(CI) ...
  *

  + CategoryInfo          : NotSpecified: (CREATOR OWNER: ...t durchgef�hrt.:String) [], RemoteException

  + FullyQualifiedErrorId : NativeCommandError

**Comment by tomcek42** [comment]
Yes, I do.

**Comment by vBrit** [comment]
Could you provide a screenshot of the permissions set?

Also, what OS and version?

**Comment by tomcek42** [comment]
Easy fix: I changed in line 62 "CREATOR OWNER" to "ERSTELLER-BESITZER" because it's a german language Windows Server 2019.
